language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python tests.py
notifications:
  webhooks: https://hooks.slack.com/services/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
    